# Generated by Django 5.2.3 on 2025-07-27 16:23

import apps.core.utils.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("action", "0030_alter_cycle_options"),
        ("character", "0042_character_template"),
        ("world", "0013_positionconnection_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("duel", models.BooleanField(default=False)),
                ("current_round", models.PositiveIntegerField(default=1)),
                ("open", models.BooleanField(default=True)),
                (
                    "attacker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fights_initiated",
                        to="character.character",
                    ),
                ),
                (
                    "created",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fights_started",
                        to="action.cycle",
                    ),
                ),
                (
                    "defender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fights_attacked",
                        to="character.character",
                    ),
                ),
                (
                    "ended_at",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fights_ended",
                        to="action.cycle",
                    ),
                ),
                (
                    "pending_join",
                    models.ManyToManyField(
                        blank=True,
                        related_name="fights_pending_join",
                        to="character.character",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fights",
                        to="world.position",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(apps.core.utils.models.Tagged, models.Model),
        ),
    ]
