# Generated by Django 5.1.4 on 2025-01-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duelinvitation',
            name='initiator',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='duelinvitation',
            name='target',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='fight',
            name='initiator',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='fight',
            name='target',
            field=models.UUIDField(),
        ),
    ]
