# Generated by Django 5.2.3 on 2025-07-27 18:31

import django.db.models.deletion
from django.db import migrations, models


def populate_fight_campaign(apps, schema_editor):
    """
    Populate the campaign field for existing fights based on their created cycle.
    """
    Fight = apps.get_model('fight', 'Fight')

    for fight in Fight.objects.all():
        if fight.created and fight.created.campaign:
            fight.campaign = fight.created.campaign
            fight.save(update_fields=['campaign'])
        else:
            # If fight has no created cycle, we need to handle this case
            # This should not happen in normal operation, but we'll log it
            print(f"Warning: Fight {fight.id} has no created cycle or cycle has no campaign")


def reverse_populate_fight_campaign(apps, schema_editor):
    """
    Reverse migration - nothing to do since we're just removing the field
    """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("fight", "0001_initial"),
        ("game", "0009_campaign_auto_play"),
    ]

    operations = [
        # First add the field as nullable
        migrations.AddField(
            model_name="fight",
            name="campaign",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fights",
                to="game.campaign",
            ),
        ),
        # Then populate the field with correct values
        migrations.RunPython(
            populate_fight_campaign,
            reverse_populate_fight_campaign,
        ),
        # Finally make the field non-nullable
        migrations.AlterField(
            model_name="fight",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fights",
                to="game.campaign",
            ),
        ),
    ]
