# Generated by Django 5.0.6 on 2024-06-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fight", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fightturnaction",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fightturnaction",
            name="order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
