# Generated by Django 5.1.4 on 2025-01-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0002_alter_duelinvitation_initiator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fight',
            name='side_a_participants',
        ),
        migrations.RemoveField(
            model_name='fight',
            name='side_b_participants',
        ),
    ]
