# Generated by Django 5.2.4 on 2025-08-03 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fight", "0003_add_characters_pending_join_fight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fight",
            name="pending_join",
        ),
    ]
