# Generated by Django 5.1.4 on 2025-01-01 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0017_alter_characterbiography_character'),
        ('fight', '0003_remove_fight_side_a_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='side_a_participants',
            field=models.ManyToManyField(blank=True, related_name='fights_side_a', to='character.character'),
        ),
        migrations.AddField(
            model_name='fight',
            name='side_b_participants',
            field=models.ManyToManyField(blank=True, related_name='fights_side_b', to='character.character'),
        ),
        migrations.AlterField(
            model_name='duelinvitation',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duel_invitations_sent', to='character.character'),
        ),
        migrations.AlterField(
            model_name='duelinvitation',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duel_invitations_received', to='character.character'),
        ),
        migrations.AlterField(
            model_name='fight',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights_initiated', to='character.character'),
        ),
        migrations.AlterField(
            model_name='fight',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights_attacked', to='character.character'),
        ),
    ]
