# Generated by Django 5.1.4 on 2025-01-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0004_fight_side_a_participants_fight_side_b_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fightturnaction',
            name='order',
        ),
    ]
