# Generated by Django 5.0.6 on 2024-12-21 10:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0014_alter_stat_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/items/')),
                ('type', models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('artifact', 'Potion'), ('amulet', 'Food'), ('material', 'Material'), ('quest', 'Quest'), ('misc', 'Misc')], default='misc', max_length=255)),
                ('weight', models.FloatField()),
                ('ap_cost', models.IntegerField(default=1)),
                ('hp_cost', models.IntegerField(default=0)),
                ('ep_cost', models.IntegerField(default=0)),
                ('once_per_fight', models.BooleanField(default=False)),
                ('once_per_turn', models.BooleanField(default=False)),
                ('once', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipped_items', to='player.player')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
