# Generated by Django 5.1.4 on 2025-01-01 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('items', '0003_alter_characteritem_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldItem',
            fields=[
                ('gameobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.gameobject')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.gameobject',),
        ),
    ]
