# Generated by Django 5.1.4 on 2025-01-01 18:36

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_worlditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=apps.core.models.ItemType.choices, default=apps.core.models.ItemType['MISC'], max_length=255),
        ),
    ]
