# Generated by Django 5.1.4 on 2025-01-01 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effects', '0003_alter_activeeffect_target'),
        ('items', '0005_alter_item_type'),
        ('school', '0003_alter_skill_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ap_cost',
        ),
        migrations.RemoveField(
            model_name='item',
            name='ep_cost',
        ),
        migrations.RemoveField(
            model_name='item',
            name='hp_cost',
        ),
        migrations.RemoveField(
            model_name='item',
            name='once',
        ),
        migrations.RemoveField(
            model_name='item',
            name='once_per_fight',
        ),
        migrations.RemoveField(
            model_name='item',
            name='once_per_turn',
        ),
        migrations.AddField(
            model_name='item',
            name='charges',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='effects.effect'),
        ),
        migrations.AddField(
            model_name='item',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.skill'),
        ),
        migrations.AddField(
            model_name='item',
            name='visibility',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='item',
            name='canonical',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
