# Generated by Django 5.1.4 on 2025-01-02 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_remove_item_ap_cost_remove_item_ep_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteritem',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='characteritem',
            name='item',
        ),
        migrations.AddField(
            model_name='characteritem',
            name='world_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='items.worlditem'),
            preserve_default=False,
        ),
    ]
