# Generated by Django 5.1.4 on 2025-01-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_remove_characteritem_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worlditem',
            name='amount',
        ),
        migrations.AddField(
            model_name='item',
            name='base_price',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='worlditem',
            name='charges_left',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
