# Generated by Django 5.1.4 on 2025-01-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_remove_worlditem_amount_item_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worlditem',
            name='visibility',
            field=models.FloatField(default=1.0),
        ),
    ]
