# Generated by Django 5.2.3 on 2025-06-24 19:36

import django.db.models.deletion
from django.db import migrations, models


def set_default_campaign(apps, schema_editor):
    Item = apps.get_model('items', 'Item')
    Campaign = apps.get_model('game', 'Campaign')

    # Get the first campaign (which should exist due to dependency on 0005_ensure_default_campaign)
    first_campaign = Campaign.objects.first()

    if first_campaign:
        # Update all existing items to use the first campaign
        Item.objects.update(campaign=first_campaign)


def reverse_func(apps, schema_editor):
    # No need to do anything when reversing
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0005_ensure_default_campaign'),
        ('items', '0009_worlditem_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='campaign',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='items', to='game.campaign'),
        ),
        migrations.RunPython(set_default_campaign, reverse_func),
    ]
