# Generated by Django 5.1.4 on 2025-02-10 21:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0028_statmodifier_applied_by_effect'),
        ('items', '0009_worlditem_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bargain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('side_a_accepted', models.BooleanField(default=False)),
                ('side_b_accepted', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('side_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bargain_initiator', to='character.character')),
                ('side_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bargain_receiver', to='character.character')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bargain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bargain.bargain')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.characteritem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bargain',
            name='side_a_offered_items',
            field=models.ManyToManyField(related_name='side_a_offered_items', to='bargain.offereditem'),
        ),
        migrations.AddField(
            model_name='bargain',
            name='side_b_offered_items',
            field=models.ManyToManyField(related_name='side_b_offered_items', to='bargain.offereditem'),
        ),
    ]
