# Generated by Django 5.1.4 on 2025-02-12 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bargain', '0001_initial'),
        ('items', '0009_worlditem_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offereditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.worlditem'),
        ),
    ]
