# Generated by Django 5.1.4 on 2025-02-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bargain', '0002_alter_offereditem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bargain',
            name='side_a_offered_items',
            field=models.ManyToManyField(blank=True, related_name='side_a_offered_items', to='bargain.offereditem'),
        ),
        migrations.AlterField(
            model_name='bargain',
            name='side_b_offered_items',
            field=models.ManyToManyField(blank=True, related_name='side_b_offered_items', to='bargain.offereditem'),
        ),
    ]
