# Generated by Django 5.0.6 on 2024-06-09 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("client", "0001_initial"),
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="main_character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="player.character",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
