# Generated by Django 5.1.4 on 2025-01-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='main_character',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
