# Generated by Django 5.1.4 on 2025-01-01 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0017_alter_characterbiography_character'),
        ('client', '0002_alter_client_main_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='main_character',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='character.character'),
        ),
    ]
