# Generated by Django 5.0.6 on 2024-06-09 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0002_initial"),
        ("player", "0004_remove_character_activities_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="main_character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="player.player",
            ),
        ),
    ]
