# Generated by Django 5.0.6 on 2024-06-09 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0003_alter_client_main_character"),
        ("player", "0008_alter_player_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="main_character",
        ),
        migrations.AddField(
            model_name="client",
            name="player",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client",
                to="player.player",
            ),
        ),
    ]
