# Generated by Django 5.1.4 on 2024-12-30 15:45

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0014_alter_stat_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(choices=apps.core.models.EffectType.choices, default=apps.core.models.EffectType['NONE'], max_length=255, primary_key=True, serialize=False)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/effects/')),
                ('permanent', models.BooleanField(default=False)),
                ('ends_in', models.PositiveIntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActiveEffect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('impact', models.JSONField(blank=True, default=dict, null=True)),
                ('active', models.BooleanField(default=True)),
                ('_data', models.JSONField(blank=True, default=dict, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_effects', to='character.character')),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='effects.effect')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
