# Generated by Django 5.1.4 on 2025-01-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeeffect',
            name='target',
            field=models.UUIDField(),
        ),
    ]
