# Generated by Django 5.1.4 on 2025-01-01 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0017_alter_characterbiography_character'),
        ('effects', '0002_alter_activeeffect_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeeffect',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='character.character'),
        ),
    ]
