# Generated by Django 5.1.4 on 2025-01-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effects', '0003_alter_activeeffect_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeeffect',
            name='ends_in',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
