# Generated by Django 5.2.4 on 2025-08-28 15:07

import apps.core.utils.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("action", "0032_characteraction_challenge"),
        ("character", "0045_character_challenge"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0009_alter_trigger_type"),
        ("game", "0010_campaign_start_position"),
        ("world", "0013_positionconnection_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="Spawner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("spawn_limit", models.PositiveIntegerField(default=1)),
                ("respawn_cycles", models.PositiveIntegerField(default=1)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.campaign"
                    ),
                ),
                (
                    "dimension",
                    models.ForeignKey(
                        blank=True,
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="world.dimension",
                    ),
                ),
                (
                    "next_spawn_cycle",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spawners_to_process",
                        to="action.cycle",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="world.position",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(apps.core.utils.models.Tagged, models.Model),
        ),
        migrations.CreateModel(
            name="SpawnedEntity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.gameobject",
                    ),
                ),
                (
                    "spawned_at",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="action.cycle",
                    ),
                ),
                (
                    "spawner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spawned_entities",
                        to="spawner.spawner",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(apps.core.utils.models.Tagged, models.Model),
        ),
        migrations.CreateModel(
            name="NPCSpawner",
            fields=[
                (
                    "spawner_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="spawner.spawner",
                    ),
                ),
                (
                    "character_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="character.charactertemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("spawner.spawner",),
        ),
    ]
