# Generated by Django 5.2.4 on 2025-08-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spawner", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spawner",
            name="next_spawn_cycle",
        ),
        migrations.AddField(
            model_name="spawner",
            name="next_spawn_cycle_number",
            field=models.BigIntegerField(
                default=0,
                editable=False,
                help_text="Cycle number when the next spawn should occur",
            ),
        ),
    ]
