# Generated by Django 5.2.4 on 2025-08-28 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_trigger_type"),
        ("spawner", "0002_remove_spawner_next_spawn_cycle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spawnedentity",
            name="game_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spawned_by",
                to="core.gameobject",
            ),
        ),
    ]
