# Generated by Django 5.0.6 on 2024-12-23 10:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('speed', models.FloatField()),
                ('energy', models.FloatField()),
                ('shift_cost', models.IntegerField(default=0)),
                ('grade', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cities/')),
                ('is_active', models.BooleanField(default=True)),
                ('border_with', models.ManyToManyField(to='world.city')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='areas/')),
                ('area', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('border_with', models.ManyToManyField(to='world.area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.city')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='continents/')),
                ('area', models.FloatField()),
                ('population', models.IntegerField()),
                ('number_of_countries', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('border_with', models.ManyToManyField(to='world.continent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='countries/')),
                ('area', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('border_with', models.ManyToManyField(to='world.country')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.continent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.country'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='locations/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.area')),
                ('border_with', models.ManyToManyField(to='world.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='planets/')),
                ('distance_from_star', models.FloatField()),
                ('diameter', models.FloatField()),
                ('mass', models.FloatField()),
                ('gravity', models.FloatField()),
                ('atmosphere', models.CharField(max_length=255)),
                ('temperature', models.FloatField()),
                ('number_of_moons', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('border_with', models.ManyToManyField(to='world.planet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='continent',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.planet'),
        ),
        migrations.CreateModel(
            name='SubLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='sub_locations/')),
                ('is_active', models.BooleanField(default=True)),
                ('border_with', models.ManyToManyField(to='world.sublocation')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
