# Generated by Django 5.0.6 on 2024-06-09 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("world", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimension",
            name="grade",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="dimension",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
