# Generated by Django 5.0.6 on 2024-12-23 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sublocation',
            name='border_with',
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('grid_x', models.BigIntegerField(default=0)),
                ('grid_y', models.BigIntegerField(default=0)),
                ('grid_z', models.BigIntegerField(default=0)),
                ('sub_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.sublocation')),
            ],
        ),
        migrations.CreateModel(
            name='PositionConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('position_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_from', to='world.position')),
                ('position_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_to', to='world.position')),
            ],
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['grid_x', 'grid_y', 'grid_z'], name='world_posit_grid_x_d3d9e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('grid_x', 'grid_y', 'grid_z')},
        ),
        migrations.AddIndex(
            model_name='positionconnection',
            index=models.Index(fields=['position_from', 'position_to'], name='world_posit_positio_50b77d_idx'),
        ),
        migrations.AddIndex(
            model_name='positionconnection',
            index=models.Index(fields=['position_to', 'position_from'], name='world_posit_positio_4b0ece_idx'),
        ),
        migrations.AddConstraint(
            model_name='positionconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('position_from__lt', models.F('position_to'))), fields=('position_from', 'position_to'), name='unique_position_connection'),
        ),
        migrations.AddConstraint(
            model_name='positionconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('position_to__lt', models.F('position_from'))), fields=('position_to', 'position_from'), name='unique_position_connection_reversed'),
        ),
    ]
