# Generated by Django 5.0.6 on 2024-12-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_remove_sublocation_border_with_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='labels',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='area',
            name='border_with',
            field=models.ManyToManyField(blank=True, to='world.area'),
        ),
        migrations.AlterField(
            model_name='city',
            name='border_with',
            field=models.ManyToManyField(blank=True, to='world.city'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='border_with',
            field=models.ManyToManyField(blank=True, to='world.continent'),
        ),
        migrations.AlterField(
            model_name='country',
            name='border_with',
            field=models.ManyToManyField(blank=True, to='world.country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='border_with',
            field=models.ManyToManyField(blank=True, to='world.location'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='border_with',
            field=models.ManyToManyField(blank=True, to='world.planet'),
        ),
    ]
