# Generated by Django 5.0.6 on 2024-12-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_position_labels_alter_area_border_with_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='positions/'),
        ),
    ]
