# Generated by Django 5.0.6 on 2024-12-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_position_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionconnection',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
