# Generated by Django 5.1.4 on 2025-01-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_positionconnection_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='is_safe',
            field=models.BooleanField(default=False),
        ),
    ]
