# Generated by Django 5.1.4 on 2025-01-23 22:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0026_alter_rank_options_rank_unique_grade_and_rank'),
        ('world', '0006_position_is_safe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='character.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MapPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('labels', models.JSONField(blank=True, default=list, null=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_positions', to='world.map')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.position')),
            ],
            options={
                'indexes': [models.Index(fields=['map', 'position'], name='world_mappo_map_id_6c8bc3_idx')],
                'unique_together': {('map', 'position')},
            },
        ),
    ]
