# Generated by Django 5.2.3 on 2025-06-23 17:13

import django.db.models.deletion
from django.db import migrations, models


def set_default_campaign(apps, schema_editor):
    Campaign = apps.get_model('game', 'Campaign')
    Dimension = apps.get_model('world', 'Dimension')

    # Get the first campaign
    if Campaign.objects.exists():
        default_campaign = Campaign.objects.first()

        # Set the campaign field for all existing Dimension instances
        for dimension in Dimension.objects.all():
            dimension.campaign = default_campaign
            dimension.save()


def reverse_func(apps, schema_editor):
    # No need to do anything when reversing
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0005_ensure_default_campaign'),
        ('world', '0007_map_mapposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='game.campaign'),
        ),
        migrations.AddField(
            model_name='city',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='game.campaign'),
        ),
        migrations.AddField(
            model_name='continent',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='game.campaign'),
        ),
        migrations.AddField(
            model_name='country',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='game.campaign'),
        ),
        # Add campaign field as nullable first
        migrations.AddField(
            model_name='dimension',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dimensions',
                                    to='game.campaign'),
        ),

        # Set default campaign for all existing instances
        migrations.RunPython(set_default_campaign, reverse_func),

        # Make the field non-nullable
        migrations.AlterField(
            model_name='dimension',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions',
                                    to='game.campaign'),
        ),
        migrations.AddField(
            model_name='location',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='game.campaign'),
        ),
        migrations.AddField(
            model_name='planet',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='game.campaign'),
        ),
        migrations.AddField(
            model_name='sublocation',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='game.campaign'),
        ),
    ]
