# Generated by Django 5.2.3 on 2025-06-25 05:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('world', '0009_set_dimension_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='city',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='continent',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='country',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='location',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='sublocation',
            name='campaign',
        ),
    ]
