# Generated by Django 5.2.3 on 2025-06-27 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("world", "0010_remove_area_campaign_remove_city_campaign_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
