# Generated by Django 5.2.3 on 2025-06-28 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("world", "0011_alter_position_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="positionconnection",
            old_name="is_locked",
            new_name="locked",
        ),
    ]
