# Generated by Django 5.2.3 on 2025-06-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("world", "0012_rename_is_locked_positionconnection_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="positionconnection",
            name="config",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
