# Generated by Django 5.0.6 on 2024-12-23 10:21

import apps.core.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionImpact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('None', 'None'), ('Knock out', 'Knock out'), ('Damage', 'Damage'), ('Heal', 'Heal'), ('Shield', 'Shield'), ('Buff', 'Buff'), ('Debuff', 'Debuff'), ('Stun', 'Stun'), ('Sleep', 'Sleep'), ('Confusion', 'Confusion'), ('Paralysis', 'Paralysis'), ('Fear', 'Fear'), ('Freeze', 'Freeze'), ('Burn', 'Burn'), ('Poison', 'Poison'), ('Slow', 'Slow'), ('Haste', 'Haste'), ('Blind', 'Blind'), ('Silence', 'Silence'), ('Bleed', 'Bleed'), ('Disarm', 'Disarm'), ('Root', 'Root'), ('Energy Decrease', 'Energy Decrease'), ('Reflect', 'Reflect'), ('Absorb', 'Absorb'), ('Dodge', 'Dodge'), ('Resist', 'Resist'), ('Immunity', 'Immunity'), ('Regeneration', 'Regeneration'), ('Lifesteal', 'Lifesteal')], max_length=255)),
                ('violation', models.CharField(choices=[('Physical', 'Physical'), ('Mental', 'Mental'), ('Energy', 'Energy'), ('Heat', 'Heat'), ('Cold', 'Cold'), ('Light', 'Light'), ('Darkness', 'Darkness'), ('None', 'None')], max_length=255)),
                ('size', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('USE_SKILL', 'USE_SKILL'), ('USE_ITEM', 'USE_ITEM'), ('DIMENSION_SHIFT', 'DIMENSION_SHIFT'), ('CHANGE_POSITION', 'CHANGE_POSITION'), ('START_DIALOGUE', 'START_DIALOGUE'), ('MAKE_DUEL_INVITATION', 'MAKE_DUEL_INVITATION'), ('ACCEPT_DUEL_INVITATION', 'ACCEPT_DUEL_INVITATION'), ('REJECT_DUEL_INVITATION', 'REJECT_DUEL_INVITATION'), ('START_FIGHT', 'START_FIGHT')], default=apps.core.models.CharacterActionType['USE_SKILL'], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiceRollResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dice_side', models.IntegerField()),
                ('multiplier', models.FloatField(null=True)),
                ('outcome', models.CharField(choices=[('Critical Fail', 'Critical Fail'), ('Critical Success', 'Critical Success'), ('Bad Luck', 'Bad Luck'), ('Base Value', 'Base Value'), ('Good Luck', 'Good Luck')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
