# Generated by Django 5.0.6 on 2024-06-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("action", "0001_initial"),
        ("player", "0010_player_school_slots"),
    ]

    operations = [
        migrations.AddField(
            model_name="playeraction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("use_skill", "Use Skill"),
                    ("use_item", "Use Item"),
                    ("dimension_shift", "Dimension Shift"),
                    ("change_position", "Change Position"),
                    ("start_dialogue", "Start Dialogue"),
                    ("make_duel_invitation", "Make Duel Invitation"),
                    ("accept_duel_invitation", "Accept Duel Invitation"),
                    ("reject_duel_invitation", "Reject Duel Invitation"),
                    ("start_fight", "Start Fight"),
                ],
                default="use_skill",
                max_length=255,
            ),
        ),
        migrations.RemoveField(
            model_name="playeraction",
            name="target",
        ),
        migrations.AddField(
            model_name="playeraction",
            name="target",
            field=models.ManyToManyField(
                related_name="actions_targets", to="player.player"
            ),
        ),
    ]
