# Generated by Django 5.0.6 on 2024-12-23 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('action', '0001_initial'),
        ('character', '0001_initial'),
        ('school', '0001_initial'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionimpact',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacted_by', to='character.character'),
        ),
        migrations.AddField(
            model_name='characteraction',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='character.character'),
        ),
        migrations.AddField(
            model_name='characteraction',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.skill'),
        ),
        migrations.AddField(
            model_name='characteraction',
            name='target_dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.dimension'),
        ),
        migrations.AddField(
            model_name='characteraction',
            name='target_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.location'),
        ),
        migrations.AddField(
            model_name='characteraction',
            name='targets',
            field=models.ManyToManyField(related_name='actions_targets', to='character.character'),
        ),
        migrations.AddField(
            model_name='actionimpact',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='action.characteraction'),
        ),
        migrations.AddField(
            model_name='actionimpact',
            name='dice_roll_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='action.dicerollresult'),
        ),
    ]
