# Generated by Django 5.1.4 on 2024-12-26 10:19

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='characteraction',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='characteraction',
            name='action_type',
            field=models.CharField(choices=[('USE_SKILL', 'USE_SKILL'), ('USE_ITEM', 'USE_ITEM'), ('DIMENSION_SHIFT', 'DIMENSION_SHIFT'), ('CHANGE_POSITION', 'CHANGE_POSITION'), ('START_DIALOGUE', 'START_DIALOGUE'), ('MAKE_DUEL_INVITATION', 'MAKE_DUEL_INVITATION'), ('ACCEPT_DUEL_INVITATION', 'ACCEPT_DUEL_INVITATION'), ('REJECT_DUEL_INVITATION', 'REJECT_DUEL_INVITATION'), ('START_FIGHT', 'START_FIGHT'), ('MOVE', 'MOVE'), ('BACK_TO_SAFE_ZONE', 'BACK_TO_SAFE_ZONE'), ('DICE_ROLL', 'DICE_ROLL')], default=apps.core.models.CharacterActionType['USE_SKILL'], max_length=255),
        ),
        migrations.AddField(
            model_name='characteraction',
            name='cycle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='action.cycle'),
            preserve_default=False,
        ),
    ]
