# Generated by Django 5.0.6 on 2024-06-22 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("action", "0002_playeraction_action_type_remove_playeraction_target_and_more"),
        ("school", "0005_skill_type"),
        ("world", "0002_dimension_grade_dimension_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playeraction",
            old_name="target",
            new_name="targets",
        ),
        migrations.AddField(
            model_name="playeraction",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.skill",
            ),
        ),
        migrations.AddField(
            model_name="playeraction",
            name="target_dimension",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="world.dimension",
            ),
        ),
        migrations.AddField(
            model_name="playeraction",
            name="target_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="world.location",
            ),
        ),
    ]
