# Generated by Django 5.1.4 on 2024-12-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_cycle_characteraction_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteraction',
            name='target_dimension',
        ),
        migrations.RemoveField(
            model_name='characteraction',
            name='target_location',
        ),
    ]
