# Generated by Django 5.0.6 on 2024-06-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("action", "0003_rename_target_playeraction_targets_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playeraction",
            name="impact",
            field=models.JSONField(default=dict),
        ),
    ]
