# Generated by Django 5.1.4 on 2024-12-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0004_remove_characteraction_target_dimension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteraction',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
