# Generated by Django 5.1.4 on 2024-12-26 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0005_characteraction_data'),
        ('character', '0012_alter_rank_experience_needed'),
        ('world', '0005_positionconnection_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteraction',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.position'),
        ),
        migrations.AlterField(
            model_name='characteraction',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='actions_targets', to='character.character'),
        ),
    ]
