# Generated by Django 5.1.4 on 2024-12-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0006_characteraction_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteraction',
            name='performed',
            field=models.BooleanField(default=False),
        ),
    ]
