# Generated by Django 5.1.4 on 2024-12-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0007_characteraction_performed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characteraction',
            old_name='approved',
            new_name='accepted',
        ),
    ]
