# Generated by Django 5.1.4 on 2024-12-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0008_rename_approved_characteraction_accepted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteraction',
            options={'ordering': ['-cycle', '-created_at']},
        ),
    ]
