# Generated by Django 5.1.4 on 2025-01-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0009_alter_characteraction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionimpact',
            name='target',
            field=models.UUIDField(),
        ),
    ]
