# Generated by Django 5.1.4 on 2025-01-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0010_alter_actionimpact_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteraction',
            name='initiator',
            field=models.UUIDField(),
        ),
    ]
