# Generated by Django 5.1.4 on 2025-01-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0011_alter_characteraction_initiator'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteraction',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='actions_targets', to='core.gameobject'),
        ),
    ]
