# Generated by Django 5.1.4 on 2025-01-01 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0012_alter_characteraction_targets'),
        ('character', '0017_alter_characterbiography_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionimpact',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacted_by', to='character.character'),
        ),
        migrations.AlterField(
            model_name='characteraction',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='character.character'),
        ),
    ]
