# Generated by Django 5.1.4 on 2025-01-02 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0013_alter_actionimpact_target_and_more'),
        ('items', '0008_remove_worlditem_amount_item_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteraction',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.worlditem'),
        ),
    ]
