# Generated by Django 5.1.4 on 2025-01-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0014_characteraction_item'),
        # ('fight', '0005_remove_fightturnaction_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteraction',
            name='order',
            field=models.FloatField(default=1),
        ),
    ]
