# Generated by Django 5.1.4 on 2025-01-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0015_characteraction_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteraction',
            options={'ordering': ['-cycle', '-order']},
        ),
    ]
