# Generated by Django 5.1.4 on 2025-01-04 15:52

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0016_alter_characteraction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteraction',
            name='action_type',
            field=models.CharField(choices=[('USE_SKILL', 'USE_SKILL'), ('USE_ITEM', 'USE_ITEM'), ('DIMENSION_SHIFT', 'DIMENSION_SHIFT'), ('CHANGE_POSITION', 'CHANGE_POSITION'), ('START_DIALOGUE', 'START_DIALOGUE'), ('MAKE_DUEL_INVITATION', 'MAKE_DUEL_INVITATION'), ('ACCEPT_DUEL_INVITATION', 'ACCEPT_DUEL_INVITATION'), ('REJECT_DUEL_INVITATION', 'REJECT_DUEL_INVITATION'), ('START_FIGHT', 'START_FIGHT'), ('MOVE', 'MOVE'), ('BACK_TO_SAFE_ZONE', 'BACK_TO_SAFE_ZONE'), ('DICE_ROLL', 'DICE_ROLL'), ('LONG_REST', 'LONG_REST')], default=apps.core.models.CharacterActionType['USE_SKILL'], max_length=255),
        ),
    ]
