# Generated by Django 5.1.4 on 2025-01-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0017_alter_characteraction_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteraction',
            name='immediate',
            field=models.BooleanField(default=False),
        ),
    ]
