# Generated by Django 5.1.4 on 2025-01-18 15:55

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0018_characteraction_immediate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialAction',
            fields=[
                ('action_type', models.CharField(choices=[('INSPECT', 'INSPECT'), ('SNATCH_ITEM', 'SNATCH_ITEM'), ('LONG_REST', 'LONG_REST'), ('BACK_TO_SAFE_ZONE', 'BACK_TO_SAFE_ZONE')], max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('immediate', models.BooleanField(default=False)),
                ('ap_cost', models.IntegerField(default=1)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/specialActions')),
            ],
        ),
        migrations.AlterField(
            model_name='characteraction',
            name='action_type',
            field=models.CharField(choices=[('USE_SKILL', 'USE_SKILL'), ('USE_ITEM', 'USE_ITEM'), ('DIMENSION_SHIFT', 'DIMENSION_SHIFT'), ('CHANGE_POSITION', 'CHANGE_POSITION'), ('START_DIALOGUE', 'START_DIALOGUE'), ('MAKE_DUEL_INVITATION', 'MAKE_DUEL_INVITATION'), ('ACCEPT_DUEL_INVITATION', 'ACCEPT_DUEL_INVITATION'), ('REJECT_DUEL_INVITATION', 'REJECT_DUEL_INVITATION'), ('START_FIGHT', 'START_FIGHT'), ('MOVE', 'MOVE'), ('DICE_ROLL', 'DICE_ROLL'), ('LONG_REST', 'LONG_REST'), ('BACK_TO_SAFE_ZONE', 'BACK_TO_SAFE_ZONE'), ('INSPECT', 'INSPECT'), ('SNATCH_ITEM', 'SNATCH_ITEM')], default=apps.core.models.CharacterActionType['USE_SKILL'], max_length=255),
        ),
    ]
