# Generated by Django 5.1.4 on 2025-01-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0019_specialaction_alter_characteraction_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialaction',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
