# Generated by Django 5.1.4 on 2025-01-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0020_specialaction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialaction',
            name='final',
            field=models.BooleanField(default=False, help_text='If true, the action will spend all remaining action points'),
        ),
        migrations.AlterField(
            model_name='specialaction',
            name='ap_cost',
            field=models.IntegerField(blank=True, default=1, help_text='Action Points cost', null=True),
        ),
        migrations.AlterField(
            model_name='specialaction',
            name='immediate',
            field=models.BooleanField(default=False, help_text='If true, the action will be performed immediately'),
        ),
    ]
