# Generated by Django 5.1.4 on 2025-01-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0021_specialaction_final_alter_specialaction_ap_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialaction',
            name='ap_cost',
        ),
        migrations.AddField(
            model_name='specialaction',
            name='cost',
            field=models.JSONField(default=list),
        ),
    ]
