# Generated by Django 5.1.4 on 2025-02-15 09:04

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0022_remove_specialaction_ap_cost_specialaction_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteraction',
            name='action_type',
            field=models.CharField(choices=[('USE_SKILL', 'USE_SKILL'), ('USE_ITEM', 'USE_ITEM'), ('DIMENSION_SHIFT', 'DIMENSION_SHIFT'), ('CHANGE_POSITION', 'CHANGE_POSITION'), ('START_DIALOGUE', 'START_DIALOGUE'), ('MAKE_DUEL_INVITATION', 'MAKE_DUEL_INVITATION'), ('ACCEPT_DUEL_INVITATION', 'ACCEPT_DUEL_INVITATION'), ('REJECT_DUEL_INVITATION', 'REJECT_DUEL_INVITATION'), ('START_FIGHT', 'START_FIGHT'), ('MOVE', 'MOVE'), ('DICE_ROLL', 'DICE_ROLL'), ('GIFT', 'GIFT'), ('LONG_REST', 'LONG_REST'), ('BACK_TO_SAFE_ZONE', 'BACK_TO_SAFE_ZONE'), ('INSPECT', 'INSPECT'), ('SNATCH_ITEM', 'SNATCH_ITEM')], default=apps.core.models.CharacterActionType['USE_SKILL'], max_length=255),
        ),
        migrations.AlterField(
            model_name='specialaction',
            name='action_type',
            field=models.CharField(choices=[('INSPECT', 'INSPECT'), ('SNATCH_ITEM', 'SNATCH_ITEM'), ('BARGAIN', 'BARGAIN'), ('GIFT', 'GIFT'), ('LONG_REST', 'LONG_REST'), ('BACK_TO_SAFE_ZONE', 'BACK_TO_SAFE_ZONE')], max_length=255, primary_key=True, serialize=False),
        ),
    ]
