# Generated by Django 5.2.3 on 2025-06-23 17:13

import django.db.models.deletion
from django.db import migrations, models


def set_default_campaign(apps, schema_editor):
    Campaign = apps.get_model('game', 'Campaign')
    CharacterAction = apps.get_model('action', 'CharacterAction')
    Cycle = apps.get_model('action', 'Cycle')

    # Get the first campaign
    if Campaign.objects.exists():
        default_campaign = Campaign.objects.first()

        # Set the campaign field for all existing CharacterAction instances
        for action in CharacterAction.objects.all():
            action.campaign = default_campaign
            action.save()

        # Set the campaign field for all existing Cycle instances
        for cycle in Cycle.objects.all():
            cycle.campaign = default_campaign
            cycle.save()


def reverse_func(apps, schema_editor):
    # No need to do anything when reversing
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('action', '0025_alter_characteraction_action_type'),
        ('game', '0005_ensure_default_campaign'),
    ]

    operations = [
        # Add campaign field as nullable first
        migrations.AddField(
            model_name='characteraction',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions',
                                    to='game.campaign'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycles',
                                    to='game.campaign'),
        ),

        # Set default campaign for all existing instances
        migrations.RunPython(set_default_campaign, reverse_func),

        # Make the fields non-nullable
        migrations.AlterField(
            model_name='characteraction',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions',
                                    to='game.campaign'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles',
                                    to='game.campaign'),
        ),
    ]
