# Generated by Django 5.2.3 on 2025-06-24 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('action', '0027_set_characteraction_cycle_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteraction',
            name='campaign',
        ),
    ]
