# Generated by Django 5.2.3 on 2025-06-27 16:08

from django.db import migrations, models


def set_cycle_numbers(apps, schema_editor):
    """
    Set the number field for existing Cycle records based on their id values.
    This ensures that each cycle has a unique number within its campaign.
    """
    Cycle = apps.get_model('action', 'Cycle')
    # Group cycles by campaign
    campaigns = {}
    for cycle in Cycle.objects.all():
        if cycle.campaign_id not in campaigns:
            campaigns[cycle.campaign_id] = []
        campaigns[cycle.campaign_id].append(cycle)

    # For each campaign, set cycle numbers based on id
    for campaign_id, cycles in campaigns.items():
        # Sort cycles by id to maintain order
        sorted_cycles = sorted(cycles, key=lambda c: c.id)
        for i, cycle in enumerate(sorted_cycles):
            cycle.number = i
            cycle.save(update_fields=['number'])


class Migration(migrations.Migration):
    dependencies = [
        ("action", "0028_remove_characteraction_campaign"),
        ("game", "0005_ensure_default_campaign"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cycle",
            options={"ordering": ["-number"]},
        ),
        migrations.AddField(
            model_name="cycle",
            name="number",
            field=models.BigIntegerField(
                default=0, help_text="Cycle number in the campaign", editable=False
            ),
        ),
        # Run data migration to set cycle numbers based on id
        migrations.RunPython(set_cycle_numbers, reverse_code=migrations.RunPython.noop),
        # Apply unique constraint after setting numbers
        migrations.AlterUniqueTogether(
            name="cycle",
            unique_together={("number", "campaign")},
        ),
    ]
