# Generated by Django 5.2.3 on 2025-06-28 05:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("action", "0029_alter_cycle_options_cycle_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cycle",
            options={"ordering": ["number"]},
        ),
    ]
