# Generated by Django 5.2.3 on 2025-07-27 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("action", "0030_alter_cycle_options"),
        ("fight", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="characteraction",
            name="fight",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="fight.fight",
            ),
        ),
    ]
