# Generated by Django 5.2.4 on 2025-08-28 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("action", "0031_characteraction_fight"),
        ("dice", "0002_challenge_advantage_challenge_disadvantage"),
    ]

    operations = [
        migrations.AddField(
            model_name="characteraction",
            name="challenge",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action",
                to="dice.challenge",
            ),
        ),
    ]
