# Generated by Django 5.0.6 on 2024-06-09 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
        ("player", "0004_remove_character_activities_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="player.player"
            ),
        ),
    ]
