# Generated by Django 5.1.4 on 2025-01-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='character',
            field=models.UUIDField(),
        ),
    ]
