# Generated by Django 5.2.3 on 2025-06-24 10:00

from django.db import migrations


def ensure_default_campaign(apps, schema_editor):
    Campaign = apps.get_model('game', 'Campaign')
    if not Campaign.objects.exists():
        Campaign.objects.create(
            name='Default Campaign',
            description='Default campaign created automatically',
            is_active=True,
            is_completed=False
        )


def reverse_func(apps, schema_editor):
    # No need to delete the default campaign when reversing
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0004_alter_session_character'),
    ]

    operations = [
        migrations.RunPython(ensure_default_campaign, reverse_func),
    ]
