# Generated by Django 5.2.3 on 2025-06-28 05:13

from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def update_client_campaigns(apps, schema_editor):
    """
    Find all non-NPC Characters and update the play_campaigns for their owners (Clients).
    Also set the current_campaign based on the character's campaign.
    """
    Character = apps.get_model('character', 'Character')
    Client = apps.get_model('client', 'Client')
    Campaign = apps.get_model('game', 'Campaign')
    GameObject = apps.get_model('core', 'GameObject')

    # Get all non-NPC characters that are active
    non_npc_characters = Character.objects.filter(
        npc=False,
        owner__isnull=False,
        gameobject_ptr__campaign__isnull=False
    )

    # Track processed client-campaign pairs to avoid duplicates
    processed_pairs = set()

    # Process each character and update their owner's campaigns
    for character in non_npc_characters:
        client = character.owner
        # Access campaign through gameobject_ptr since Character is polymorphic
        campaign = GameObject.objects.get(pk=character.gameobject_ptr_id).campaign

        if client and campaign:
            # Create a unique key for this client-campaign pair
            pair_key = (client.id, campaign.id)

            # Only process if we haven't seen this pair before
            if pair_key not in processed_pairs:
                processed_pairs.add(pair_key)

                # Add the campaign to the client's play_campaigns
                client.play_campaigns.add(campaign)

            # If this is the client's main character, set current_campaign
            if hasattr(client, 'main_character') and client.main_character == character:
                client.current_campaign = campaign
                client.save(update_fields=['current_campaign'])


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0005_ensure_default_campaign"),
        ("client", "0004_client_current_campaign"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="masters",
            field=models.ManyToManyField(
                blank=True, related_name="master_campaigns", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="players",
            field=models.ManyToManyField(
                blank=True, related_name="play_campaigns", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RunPython(update_client_campaigns, migrations.RunPython.noop),
    ]
