# Generated by Django 5.2.3 on 2025-06-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0006_campaign_masters_campaign_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="background_image",
            field=models.ImageField(blank=True, null=True, upload_to="campaigns/"),
        ),
    ]
