# Generated by Django 5.2.3 on 2025-06-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0007_campaign_background_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="default",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this is the default campaign for new clients.",
            ),
        ),
    ]
