# Generated by Django 5.2.3 on 2025-07-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0008_campaign_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="auto_play",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this campaign is set for auto-play.",
            ),
        ),
    ]
