# Generated by Django 5.2.4 on 2025-08-28 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0009_campaign_auto_play"),
        ("world", "0013_positionconnection_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="start_position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="starting_campaigns",
                to="world.position",
            ),
        ),
    ]
