# Generated by Django 5.0.6 on 2024-12-23 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0001_initial'),
        ('fight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='fight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fight.fight'),
        ),
    ]
