# Generated by Django 5.0.6 on 2024-12-23 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0002_initial'),
        ('school', '0001_initial'),
        ('world', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.thepath'),
        ),
        migrations.AddField(
            model_name='character',
            name='place_of_birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='where_born', to='world.location'),
        ),
        migrations.AddField(
            model_name='character',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.organization'),
        ),
        migrations.AddField(
            model_name='rank',
            name='next_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.rank'),
        ),
        migrations.AddField(
            model_name='character',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.rank'),
        ),
        migrations.AddField(
            model_name='stat',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='character.character'),
        ),
        migrations.AddConstraint(
            model_name='stat',
            constraint=models.UniqueConstraint(fields=('name', 'character'), name='unique_stat_per_character'),
        ),
    ]
