# Generated by Django 5.0.6 on 2024-12-23 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_initial'),
        ('game', '0002_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.campaign'),
        ),
        migrations.AddField(
            model_name='character',
            name='npc',
            field=models.BooleanField(default=False),
        ),
    ]
