# Generated by Django 5.0.6 on 2024-12-23 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_character_campaign_character_npc'),
        ('world', '0003_position_labels_alter_area_border_with_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.position'),
        ),
    ]
