# Generated by Django 5.0.6 on 2024-12-23 15:38

import apps.core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_character_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='age',
        ),
        migrations.RemoveField(
            model_name='character',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='character',
            name='gender',
        ),
        migrations.CreateModel(
            name='CharacterBiography',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(900)])),
                ('gender', models.CharField(choices=apps.core.models.GenderEnum.choices, default=apps.core.models.GenderEnum['OTHER'], max_length=50)),
                ('background', models.TextField(blank=True)),
                ('appearance', models.TextField(blank=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biography', to='character.character')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
