# Generated by Django 5.0.6 on 2024-12-24 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_remove_character_age_remove_character_bio_and_more'),
        ('world', '0003_position_labels_alter_area_border_with_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='current_location',
        ),
        migrations.AddField(
            model_name='character',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='character',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='world.position'),
        ),
    ]
