# Generated by Django 5.0.6 on 2024-12-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_remove_character_current_location_character_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
