# Generated by Django 5.0.6 on 2024-12-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0008_alter_character_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='current_active_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='current_energy_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='current_health_points',
            field=models.IntegerField(default=1),
        ),
    ]
