# Generated by Django 5.0.6 on 2024-12-24 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0009_alter_character_current_active_points_and_more'),
        ('world', '0003_position_labels_alter_area_border_with_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='dimension',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.dimension'),
        ),
    ]
