# Generated by Django 5.0.6 on 2024-12-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0010_alter_character_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterbiography',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
