# Generated by Django 5.1.4 on 2024-12-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0011_characterbiography_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='experience_needed',
            field=models.BigIntegerField(),
        ),
    ]
