# Generated by Django 5.1.4 on 2024-12-29 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0012_alter_rank_experience_needed'),
        ('world', '0005_positionconnection_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='last_safe_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_in_safe', to='world.position'),
        ),
    ]
