# Generated by Django 5.1.4 on 2025-01-01 14:49
import uuid

from django.db import migrations, models


def pre_create_gameobjects(apps, schema_editor):
    GameObject = apps.get_model('core', 'GameObject')
    Character = apps.get_model('character', 'Character')
    for character in Character.objects.all():
        GameObject.objects.create(
            id=character.id,
            position=character.position,
            dimension=character.dimension,
            is_active=character.is_active,
            campaign=character.campaign
        )


class Migration(migrations.Migration):
    dependencies = [
        ('character', '0014_alter_stat_name'),
    ]

    operations = [
        migrations.RunPython(pre_create_gameobjects),
        migrations.RemoveField(
            model_name='character',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='character',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='character',
            name='dimension',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='id',
            new_name='gameobject_ptr',
        ),
        migrations.RemoveField(
            model_name='character',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='character',
            name='position',
        ),
        migrations.RemoveField(
            model_name='character',
            name='updated_at',
        ),
    ]
