# Generated by Django 5.1.4 on 2025-01-01 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
        ('character', '0015_remove_character_campaign_and_more'),
        ('skills', '0004_alter_learnedschool_character_and_more'),
        ('modificators', '0003_alter_charactermodificator_character'),
        ('items', '0002_alter_characteritem_character'),
        ('game', '0003_alter_session_character'),
        ('currency', '0002_alter_charactercurrency_character'),
        ('effects', '0002_alter_activeeffect_target'),
        ('action', '0010_alter_actionimpact_target'),
        ('action', '0011_alter_characteraction_initiator'),
        ('action', '0012_alter_characteraction_targets'),
        # ('fight', '0002_alter_duelinvitation_initiator_and_more'),
        # ('fight', '0003_remove_fight_side_a_participants_and_more'),
        ('client', '0002_alter_client_main_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterbiography',
            name='character',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='stat',
            name='character',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='character',
            name='gameobject_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                       primary_key=True, serialize=False, to='core.gameobject'),
        ),
    ]
