# Generated by Django 5.1.4 on 2025-01-01 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0016_alter_character_gameobject_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterbiography',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biography', to='character.character'),
        ),
    ]
