# Generated by Django 5.1.4 on 2025-01-01 15:51

from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def set_polymorphic_ctype(apps, schema_editor):
    Character = apps.get_model('character', 'Character')
    content_type = ContentType.objects.get_for_model(Character, for_concrete_model=False)
    GameObject = apps.get_model('core', 'GameObject')

    for character in Character.objects.all():
        GameObject.objects.filter(pk=character.pk).update(polymorphic_ctype=content_type)

class Migration(migrations.Migration):
    dependencies = [
        ('character', '0018_alter_stat_character'),
    ]

    operations = [
        migrations.RunPython(set_polymorphic_ctype),
    ]
