# Generated by Django 5.1.4 on 2025-01-12 11:01
from django.db import migrations, models


def create_base_stats(apps, schema_editor):
    from apps.game.services.character.character_base_stats import CharacterBaseStatsService
    from apps.game.services.rand_dice import DiceService
    import logging

    logger = logging.getLogger(__name__)

    # Dynamically get models
    Character = apps.get_model('character', 'Character')
    Stat = apps.get_model('character', 'Stat')
    DiceRollResult = apps.get_model('action', 'DiceRollResult')
    for character in Character.objects.all():
        try:
            logger.info(f"Resetting base stats for character {character}")
            svc = CharacterBaseStatsService(character, DiceService)
            svc.statModel = Stat
            svc.diceRollModel = DiceRollResult
            svc.reset_base_stats()
        except Exception as e:
            logger.error(f"Error while resetting base stats for character {character}: {e}")
            raise e


class Migration(migrations.Migration):
    dependencies = [
        ('action', '0017_alter_characteraction_action_type'),
        ('character', '0019_fix_content_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='base_value',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat',
            name='dice_rolls',
            field=models.ManyToManyField(related_name='base_stat_results', to='action.dicerollresult'),
        ),
        migrations.RunPython(
            create_base_stats,
            migrations.RunPython.noop
        ),
    ]
