# Generated by Django 5.1.4 on 2025-01-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0020_stat_base_value_stat_dice_rolls'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='resetting_base_stats',
            field=models.BooleanField(default=False),
        ),
    ]
