# Generated by Django 5.1.4 on 2025-01-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0021_character_resetting_base_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='value',
            new_name='additional_value',
        ),
    ]
