# Generated by Django 5.1.4 on 2025-01-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0022_rename_value_stat_additional_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='additional_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stat',
            name='base_value',
            field=models.IntegerField(default=0),
        ),
    ]
