# Generated by Django 5.1.4 on 2025-01-12 16:31

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0023_alter_stat_additional_value_alter_stat_base_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='behavior',
            field=models.CharField(choices=[('Passive', 'Passive'), ('Aggressive', 'Aggressive'), ('Friendly', 'Friendly')], db_index=True, default=apps.core.models.BehaviorModel['PASSIVE'], max_length=20),
        ),
    ]
