# Generated by Django 5.1.4 on 2025-01-21 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0024_character_behavior'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rank',
            options={'ordering': ['grade'], 'verbose_name_plural': 'Ranks'},
        ),
        migrations.AddField(
            model_name='rank',
            name='additional_stat_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rank',
            name='grade_rank',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='rank',
            name='experience_needed',
            field=models.BigIntegerField(default=0),
        ),
    ]
