# Generated by Django 5.1.4 on 2025-01-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0025_alter_rank_options_rank_additional_stat_points_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rank',
            options={'ordering': ['grade', 'grade_rank'], 'verbose_name': 'Rank', 'verbose_name_plural': 'Ranks'},
        ),
        migrations.AddConstraint(
            model_name='rank',
            constraint=models.UniqueConstraint(fields=('grade', 'grade_rank'), name='unique_grade_and_rank'),
        ),
    ]
