# Generated by Django 5.1.4 on 2025-01-28 06:15

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0026_alter_rank_options_rank_unique_grade_and_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatModifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Physical Strength', 'Physical Strength'), ('Mental Strength', 'Mental Strength'), ('Flow Resonance', 'Flow Resonance'), ('Concentration', 'Concentration'), ('Flow Manipulation', 'Flow Manipulation'), ('Flow Connection', 'Flow Connection'), ('Knowledge', 'Knowledge'), ('Speed', 'Speed'), ('Luck', 'Luck'), ('Charisma', 'Charisma')], default=apps.core.models.CharacterStats['PHYSICAL_STRENGTH'], max_length=255)),
                ('value', models.IntegerField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_modifiers', to='character.character')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
