# Generated by Django 5.1.4 on 2025-01-28 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0027_statmodifier'),
        ('effects', '0003_alter_activeeffect_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='statmodifier',
            name='applied_by_effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_stat_modifiers', to='effects.activeeffect'),
        ),
    ]
