# Generated by Django 5.1.4 on 2025-02-15 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0028_statmodifier_applied_by_effect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='fight',
        ),
    ]
