# Generated by Django 5.1.4 on 2025-06-21 11:37

import apps.core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0029_remove_character_fight'),
        ('game', '0004_alter_session_character'),
        ('items', '0009_worlditem_visibility'),
        ('school', '0008_skill_immediate'),
        ('world', '0007_map_mapposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterBiographyTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('age_min', models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(900)])),
                ('age_max', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(900)])),
                ('gender', models.CharField(choices=apps.core.models.GenderEnum.choices, default=apps.core.models.GenderEnum['OTHER'], max_length=50)),
                ('randomize_gender', models.BooleanField(default=False)),
                ('background', models.TextField(blank=True)),
                ('appearance', models.TextField(blank=True)),
                ('background_variations', models.JSONField(blank=True, default=list, help_text='List of background variations to choose from randomly')),
                ('appearance_variations', models.JSONField(blank=True, default=list, help_text='List of appearance variations to choose from randomly')),
                ('avatar', models.ImageField(blank=True, help_text='Avatar image for the character', upload_to='avatars/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterStatsTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('behavior', models.CharField(choices=[('Passive', 'Passive'), ('Aggressive', 'Aggressive'), ('Friendly', 'Friendly')], default=apps.core.models.BehaviorModel['PASSIVE'], max_length=20)),
                ('health_multiplier', models.FloatField(default=1.0, help_text='Multiplier for calculated health based on Physical Strength')),
                ('energy_multiplier', models.FloatField(default=1.0, help_text='Multiplier for calculated energy based on Mental Strength')),
                ('action_points_multiplier', models.FloatField(default=1.0, help_text='Multiplier for calculated action points based on Speed')),
                ('randomize_name', models.BooleanField(default=False, help_text='Generate random names for NPCs created from this template')),
                ('name_pattern', models.CharField(blank=True, help_text="Pattern for name generation, e.g., '{base_name} {number}'", max_length=255)),
                ('biography_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.characterbiographytemplate')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.campaign')),
                ('dimension', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.dimension')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.organization')),
                ('path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.thepath')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.rank')),
                ('stats_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.characterstatstemplate')),
            ],
            options={
                'verbose_name': 'Character Template',
                'verbose_name_plural': 'Character Templates',
            },
        ),
        migrations.CreateModel(
            name='CharacterNameTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_type', models.CharField(choices=[('first_name', 'First Name'), ('last_name', 'Last Name'), ('full_name', 'Full Name'), ('nickname', 'Nickname'), ('title', 'Title')], max_length=50)),
                ('names', models.JSONField(default=list, help_text='List of names to choose from randomly')),
                ('gender_specific', models.CharField(blank=True, choices=apps.core.models.GenderEnum.choices, help_text='If set, only use for this gender', max_length=50)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_templates', to='character.charactertemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterModifierTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stat', models.CharField(choices=[('Physical Strength', 'Physical Strength'), ('Mental Strength', 'Mental Strength'), ('Flow Resonance', 'Flow Resonance'), ('Concentration', 'Concentration'), ('Flow Manipulation', 'Flow Manipulation'), ('Flow Connection', 'Flow Connection'), ('Knowledge', 'Knowledge'), ('Speed', 'Speed'), ('Luck', 'Luck'), ('Charisma', 'Charisma')], max_length=255)),
                ('value', models.IntegerField(help_text='Modifier value (can be positive or negative)')),
                ('description', models.CharField(blank=True, help_text='Description of what causes this modifier', max_length=255)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_templates', to='character.charactertemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterStatTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stat', models.CharField(choices=[('Physical Strength', 'Physical Strength'), ('Mental Strength', 'Mental Strength'), ('Flow Resonance', 'Flow Resonance'), ('Concentration', 'Concentration'), ('Flow Manipulation', 'Flow Manipulation'), ('Flow Connection', 'Flow Connection'), ('Knowledge', 'Knowledge'), ('Speed', 'Speed'), ('Luck', 'Luck'), ('Charisma', 'Charisma')], max_length=255)),
                ('value', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='character.characterstatstemplate')),
            ],
            options={
                'unique_together': {('template', 'stat')},
            },
        ),
        migrations.CreateModel(
            name='CharacterSkillTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_base', models.BooleanField(default=False)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.skill')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_templates', to='character.charactertemplate')),
            ],
            options={
                'unique_together': {('template', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='CharacterSchoolTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_base', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_templates', to='character.charactertemplate')),
            ],
            options={
                'unique_together': {('template', 'school')},
            },
        ),
        migrations.CreateModel(
            name='CharacterEquipmentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_equipped', models.BooleanField(default=False, help_text='Whether the item should be equipped automatically')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_templates', to='character.charactertemplate')),
            ],
            options={
                'unique_together': {('template', 'item')},
            },
        ),
    ]
