# Generated by Django 5.2.3 on 2025-06-21 16:29

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0031_alter_character_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0, help_text='Lower values mean higher priority')),
                ('type', models.CharField(choices=[('Teleport', 'Teleport'), ('Walk', 'Walk')], default=apps.core.models.MoveTypes['TELEPORT'], max_length=20)),
                ('cycles_left', models.IntegerField(default=0, help_text='Number of cycles to follow before stopping')),
                ('permanent', models.BooleanField(default=False, help_text='If True, the follower will always follow the leader')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='character.character')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='character.character')),
            ],
        ),
    ]
