# Generated by Django 5.2.3 on 2025-06-22 12:50

import django.db.models.deletion
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):
    dependencies = [
        ('character', '0032_followrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='behavior',
            field=models.CharField(
                choices=[('Passive', 'Passive'), ('Aggressive', 'Aggressive'), ('Friendly', 'Friendly')],
                default=apps.core.models.BehaviorModel['PASSIVE'], max_length=20),
        ),
        migrations.CreateModel(
            name='CharacterRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(
                    choices=[('Passive', 'Passive'), ('Aggressive', 'Aggressive'), ('Friendly', 'Friendly')],
                    default=apps.core.models.BehaviorModel['PASSIVE'], max_length=20)),
                ('immutable',
                 models.BooleanField(default=False, help_text='If True, the relation cannot be changed or deleted.')),
                ('character_from',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from',
                                   to='character.character')),
                ('character_to',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to',
                                   to='character.character')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(
                    choices=[('Passive', 'Passive'), ('Aggressive', 'Aggressive'), ('Friendly', 'Friendly')],
                    default=apps.core.models.BehaviorModel['PASSIVE'], max_length=20)),
                ('immutable',
                 models.BooleanField(default=False, help_text='If True, the relation cannot be changed or deleted.')),
                ('organization_from',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from',
                                   to='character.organization')),
                ('organization_to',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to',
                                   to='character.organization')),
            ],
        ),
    ]
