# Generated by Django 5.2.3 on 2025-06-23 17:13

import django.db.models.deletion
from django.db import migrations, models


def set_default_campaign(apps, schema_editor):
    Campaign = apps.get_model('game', 'Campaign')
    Organization = apps.get_model('character', 'Organization')

    # Get the first campaign
    if Campaign.objects.exists():
        default_campaign = Campaign.objects.first()

        # Set the campaign field for all existing Organization instances
        for org in Organization.objects.all():
            org.campaign = default_campaign
            org.save()


def reverse_func(apps, schema_editor):
    # No need to do anything when reversing
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('character', '0033_organization_behavior_characterrelation_and_more'),
        ('game', '0005_ensure_default_campaign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterrelation',
            options={'verbose_name': 'Character Relation', 'verbose_name_plural': 'Character Relations'},
        ),
        migrations.AlterModelOptions(
            name='organizationrelation',
            options={'verbose_name': 'Organization Relation', 'verbose_name_plural': 'Organization Relations'},
        ),
        # Add campaign field as nullable first
        migrations.AddField(
            model_name='organization',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='organizations', to='game.campaign'),
        ),

        # Set default campaign for all existing instances
        migrations.RunPython(set_default_campaign, reverse_func),

        # Make the field non-nullable
        migrations.AlterField(
            model_name='organization',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations',
                                    to='game.campaign'),
        ),
    ]
