# Generated by Django 5.2.3 on 2025-06-24 11:00

from django.db import migrations


def set_organization_campaign(apps, schema_editor):
    # This migration is no longer needed since we're using the default value in the AddField operation
    pass


def reverse_func(apps, schema_editor):
    # No need to do anything when reversing
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('character', '0034_alter_characterrelation_options_and_more'),
        ('game', '0005_ensure_default_campaign'),
    ]

    operations = [
        migrations.RunPython(set_organization_campaign, reverse_func),
    ]
