# Generated by Django 5.2.3 on 2025-06-24 11:00

from django.db import migrations


def set_models_campaign(apps, schema_editor):
    # Get the Campaign model
    Campaign = apps.get_model('game', 'Campaign')

    # Find the first active, not completed campaign
    campaign = Campaign.objects.filter(is_active=True, is_completed=False).first()

    if not campaign:
        # If no active, not completed campaign exists, we can't proceed
        return

    # Get all the models that need to be updated
    GameObject = apps.get_model('core', 'GameObject')
    Organization = apps.get_model('character', 'Organization')
    CharacterTemplate = apps.get_model('character', 'CharacterTemplate')
    Dimension = apps.get_model('world', 'Dimension')
    Planet = apps.get_model('world', 'Planet')
    Continent = apps.get_model('world', 'Continent')
    Country = apps.get_model('world', 'Country')
    City = apps.get_model('world', 'City')
    Area = apps.get_model('world', 'Area')
    Location = apps.get_model('world', 'Location')
    SubLocation = apps.get_model('world', 'SubLocation')
    Cycle = apps.get_model('action', 'Cycle')
    CharacterAction = apps.get_model('action', 'CharacterAction')

    # Update all GameObject instances (this includes Character, WorldItem, etc.)
    GameObject.objects.filter(campaign__isnull=True).update(campaign=campaign)

    # Update models that don't inherit from GameObject
    Organization.objects.filter(campaign__isnull=True).update(campaign=campaign)
    CharacterTemplate.objects.filter(campaign__isnull=True).update(campaign=campaign)
    Dimension.objects.filter(campaign__isnull=True).update(campaign=campaign)
    Planet.objects.filter(campaign__isnull=True).update(campaign=campaign)
    Continent.objects.filter(campaign__isnull=True).update(campaign=campaign)
    Country.objects.filter(campaign__isnull=True).update(campaign=campaign)
    City.objects.filter(campaign__isnull=True).update(campaign=campaign)
    Area.objects.filter(campaign__isnull=True).update(campaign=campaign)
    Location.objects.filter(campaign__isnull=True).update(campaign=campaign)
    SubLocation.objects.filter(campaign__isnull=True).update(campaign=campaign)
    Cycle.objects.filter(campaign__isnull=True).update(campaign=campaign)
    CharacterAction.objects.filter(campaign__isnull=True).update(campaign=campaign)


def reverse_func(apps, schema_editor):
    # No need to do anything when reversing
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('character', '0035_set_organization_campaign'),
        ('items', '0009_worlditem_visibility'),
        ('world', '0009_set_dimension_campaign'),
        ('action', '0027_set_characteraction_cycle_campaign'),
        ('game', '0005_ensure_default_campaign'),
    ]

    operations = [
        migrations.RunPython(set_models_campaign, reverse_func),
    ]
