# Generated by Django 5.2.3 on 2025-06-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('character', '0036_set_models_campaign'),
        ('game', '0005_ensure_default_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactertemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='charactertemplate',
            unique_together={('name', 'campaign')},
        ),
    ]
