# Generated by Django 5.2.3 on 2025-07-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0038_alter_charactertemplate_campaign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterbiography",
            name="avatar",
            field=models.ImageField(
                blank=True, default="avatars/placeholder.png", upload_to="avatars/"
            ),
        ),
    ]
