# Generated by Django 5.2.3 on 2025-07-14 11:10

from django.db import migrations
from collections import Counter


def deduplicate_organizations_and_templates(apps, schema_editor):
    """
    Rename duplicate organizations and character templates by appending campaign name
    to avoid conflicts when making them global.
    """
    Organization = apps.get_model('character', 'Organization')
    CharacterTemplate = apps.get_model('character', 'CharacterTemplate')

    print("Starting deduplication of organizations and character templates...")

    # Handle Organizations
    print("Processing organizations...")
    org_names = list(Organization.objects.values_list('name', flat=True))
    org_counts = Counter(org_names)
    duplicate_org_names = {name: count for name, count in org_counts.items() if count > 1}

    for org_name in duplicate_org_names:
        orgs_with_name = Organization.objects.filter(name=org_name).select_related('campaign')
        print(f"  Found {len(orgs_with_name)} organizations named '{org_name}'")

        for org in orgs_with_name:
            # Append campaign name to make unique
            new_name = f"{org.name} ({org.campaign.name})"
            print(f"    Renaming '{org.name}' to '{new_name}'")
            org.name = new_name
            org.save(update_fields=['name'])

    # Handle Character Templates
    print("Processing character templates...")
    template_names = list(CharacterTemplate.objects.values_list('name', flat=True))
    template_counts = Counter(template_names)
    duplicate_template_names = {name: count for name, count in template_counts.items() if count > 1}

    for template_name in duplicate_template_names:
        templates_with_name = CharacterTemplate.objects.filter(name=template_name).select_related('campaign')
        print(f"  Found {len(templates_with_name)} templates named '{template_name}'")

        for template in templates_with_name:
            # Append campaign name to make unique
            new_name = f"{template.name} ({template.campaign.name})"
            print(f"    Renaming '{template.name}' to '{new_name}'")
            template.name = new_name
            template.save(update_fields=['name'])

    print("Deduplication completed!")


def reverse_deduplicate_organizations_and_templates(apps, schema_editor):
    """
    Reverse the deduplication by removing campaign names from organization and template names.
    This is a best-effort reverse - may not be perfect if names were manually changed.
    """
    Organization = apps.get_model('character', 'Organization')
    CharacterTemplate = apps.get_model('character', 'CharacterTemplate')

    print("Reversing deduplication...")

    # Reverse organizations
    for org in Organization.objects.all():
        if ' (' in org.name and org.name.endswith(')'):
            # Try to extract original name
            original_name = org.name.rsplit(' (', 1)[0]
            print(f"  Reverting org '{org.name}' to '{original_name}'")
            org.name = original_name
            org.save(update_fields=['name'])

    # Reverse character templates
    for template in CharacterTemplate.objects.all():
        if ' (' in template.name and template.name.endswith(')'):
            # Try to extract original name
            original_name = template.name.rsplit(' (', 1)[0]
            print(f"  Reverting template '{template.name}' to '{original_name}'")
            template.name = original_name
            template.save(update_fields=['name'])

    print("Reverse deduplication completed!")


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0039_alter_characterbiography_avatar"),
        ("game", "0001_initial"),  # Ensure Campaign model is available
    ]

    operations = [
        migrations.RunPython(
            deduplicate_organizations_and_templates,
            reverse_deduplicate_organizations_and_templates,
        ),
    ]
