# Generated by Django 5.2.3 on 2025-07-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0040_make_organizations_global_data"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="charactertemplate",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="organization",
            name="campaign",
        ),
        migrations.AlterField(
            model_name="charactertemplate",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name="charactertemplate",
            name="campaign",
        ),
    ]
