# Generated by Django 5.2.3 on 2025-07-14 11:38

import re
import django.db.models.deletion
from django.db import migrations, models, transaction


def setup_npc_template_relations(apps, schema_editor):
    """
    Setup NPC to Template relations similar to hacking/set_all_npc_template_inharit.py
    """
    Character = apps.get_model('character', 'Character')
    CharacterTemplate = apps.get_model('character', 'CharacterTemplate')

    # Import NPCFactory - we need to import it dynamically to avoid migration issues
    from apps.game.services.npc.factory import NPCFactory

    factory = NPCFactory()
    npc_characters = Character.objects.filter(npc=True, template__isnull=True)

    class TemplateResolver:
        __mapping__: dict[str, "CharacterTemplate"]
        __constant_names_patterns__ = [r'(.* Hex).*', r'(.* Prime).*']

        def __init__(self, factory: NPCFactory = factory):
            self.factory = factory
            self.__mapping__ = {}

        def internal_resolve(self, npc: "Character") -> CharacterTemplate | None:
            for name_pattern in self.__constant_names_patterns__:
                found = re.findall(rf'{name_pattern}', npc.name, re.IGNORECASE)
                if found:
                    template_name = found[0].strip()
                    print("====== Found name pattern ====", name_pattern)
                    if template_name not in self.__mapping__:
                        print("====== Creating template from NPC ====", template_name)
                        self.__mapping__[template_name] = self.factory.create_template_from_npc(
                            npc, template_name
                        )
                    return self.__mapping__[template_name]
            return None

        def lookup_template(self, npc: "Character") -> CharacterTemplate | None:
            try:
                return CharacterTemplate.objects.get(name=npc.name)
            except CharacterTemplate.DoesNotExist:
                pass

        def resolve(self, npc: "Character") -> CharacterTemplate:
            if npc.template:
                return npc.template
            template = self.internal_resolve(npc)
            if not template:
                template = self.lookup_template(npc)
                if template:
                    return template
                print("====== Creating template from NPC name ====", npc.name)
                template = self.factory.create_template_from_npc(npc, npc.name)
            return template

    with transaction.atomic():
        npc_characters = npc_characters.select_for_update()
        resolver = TemplateResolver(factory)
        for npc in npc_characters:
            if not npc.template:
                template = resolver.resolve(npc)
                npc.template_id = template.id
                npc.save(update_fields=['template'])


def reverse_npc_template_relations(apps, schema_editor):
    """
    Reverse the NPC template relations by setting them to null
    """
    Character = apps.get_model('character', 'Character')
    Character.objects.filter(npc=True).update(template=None)


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0041_alter_charactertemplate_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="character.charactertemplate",
            ),
        ),
        migrations.RunPython(
            setup_npc_template_relations,
            reverse_npc_template_relations,
        ),
    ]
