# Generated by Django 5.2.3 on 2025-07-29 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0043_character_fight"),
        ("fight", "0002_fight_campaign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="fight",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="joined",
                to="fight.fight",
            ),
        ),
    ]
