# Generated by Django 5.2.4 on 2025-08-27 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0044_alter_character_fight"),
        ("dice", "0002_challenge_advantage_challenge_disadvantage"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="challenge",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="for_character",
                to="dice.challenge",
            ),
        ),
    ]
