# Generated by Django 5.2.4 on 2025-10-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0045_character_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterbiography',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/placeholder/other.png', upload_to='avatars/'),
        ),
    ]
