# Generated by Django 5.2.4 on 2025-11-24 14:17

import apps.core.utils.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0046_alter_characterbiography_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedCharacter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('big_avatar', models.ImageField(blank=True, default='avatars/placeholder/other.png', upload_to='avatarsPublic/')),
                ('small_avatar', models.ImageField(blank=True, default='avatars/placeholder/other.png', upload_to='avatarsPublic/')),
                ('biography', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.characterbiography')),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.core.utils.models.Tagged, models.Model),
        ),
    ]
