# Generated by Django 5.2.4 on 2025-11-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0047_publishedcharacter'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedcharacter',
            name='instagram_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='publishedcharacter',
            name='tiktalk_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='publishedcharacter',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
    ]
