# Generated by Django 5.2.4 on 2025-11-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0048_publishedcharacter_instagram_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishedcharacter',
            old_name='tiktalk_link',
            new_name='tiktok_link',
        ),
    ]
