# Generated by Django 5.0.6 on 2024-12-23 10:21

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modificator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/modificators/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterModificator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificators', to='character.character')),
                ('modificator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modificators.modificator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatModificator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stat', models.CharField(choices=[('Physical Strength', 'Physical Strength'), ('Mental Strength', 'Mental Strength'), ('Luck', 'Luck'), ('Speed', 'Speed'), ('Concentration', 'Concentration'), ('Flow Manipulation', 'Flow Manipulation'), ('Flow Connection', 'Flow Connection'), ('Knowledge', 'Knowledge'), ('Flow Resonance', 'Flow Resonance'), ('Charisma', 'Charisma')], default=apps.core.models.CharacterStats['PHYSICAL_STRENGTH'], max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('modificator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modificators.modificator')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
