# Generated by Django 5.1.4 on 2024-12-30 15:45

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modificators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statmodificator',
            name='stat',
            field=models.CharField(choices=[('Physical Strength', 'Physical Strength'), ('Mental Strength', 'Mental Strength'), ('Flow Resonance', 'Flow Resonance'), ('Concentration', 'Concentration'), ('Flow Manipulation', 'Flow Manipulation'), ('Flow Connection', 'Flow Connection'), ('Knowledge', 'Knowledge'), ('Speed', 'Speed'), ('Luck', 'Luck'), ('Charisma', 'Charisma')], default=apps.core.models.CharacterStats['PHYSICAL_STRENGTH'], max_length=255),
        ),
    ]
