# Generated by Django 5.1.4 on 2025-01-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modificators', '0002_alter_statmodificator_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermodificator',
            name='character',
            field=models.UUIDField(),
        ),
    ]
