# Generated by Django 5.1.4 on 2024-12-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnedschool',
            name='is_base',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learnedskill',
            name='is_base',
            field=models.BooleanField(default=False),
        ),
    ]
