# Generated by Django 5.1.4 on 2025-01-01 10:05
from django.db import migrations


def fix_all_characters(apps, schema_editor):
    Character = apps.get_model('character', 'Character')
    School = apps.get_model('school', 'School')

    for char in Character.objects.all():
        grade = char.rank.grade
        for school in School.objects.filter(is_base=True, path=char.path):
            char.learned_schools.get_or_create(
                school=school,
                defaults={'is_base': school.is_base},
            )
            skills = school.skills.filter(grade__gte=grade)
            for skill in skills:
                char.learned_skills.get_or_create(
                    skill=skill,
                    defaults={'is_base': skill.school.is_base},
                )


class Migration(migrations.Migration):
    dependencies = [
        ('skills', '0002_learnedschool_is_base_learnedskill_is_base'),
    ]

    operations = [
        migrations.RunPython(fix_all_characters),
    ]
