# Generated by Django 5.1.4 on 2025-01-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_auto_20250101_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnedschool',
            name='character',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='learnedskill',
            name='character',
            field=models.UUIDField(),
        ),
    ]
