# Generated by Django 5.1.4 on 2025-01-01 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0017_alter_characterbiography_character'),
        ('skills', '0004_alter_learnedschool_character_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnedschool',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_schools', to='character.character'),
        ),
        migrations.AlterField(
            model_name='learnedskill',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learned_skills', to='character.character'),
        ),
    ]
