# Generated by Django 5.1.4 on 2025-01-02 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('game', '0004_alter_session_character'),
        ('world', '0005_positionconnection_is_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameobject',
            name='campaign',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.campaign'),
        ),
        migrations.AlterField(
            model_name='gameobject',
            name='position',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.position'),
        ),
    ]
