# Generated by Django 5.1.4 on 2025-01-04 15:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_alter_gameobject_campaign_alter_gameobject_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatObject',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(choices=[('Physical Strength', 'Physical Strength'), ('Mental Strength', 'Mental Strength'), ('Flow Resonance', 'Flow Resonance'), ('Concentration', 'Concentration'), ('Flow Manipulation', 'Flow Manipulation'), ('Flow Connection', 'Flow Connection'), ('Knowledge', 'Knowledge'), ('Speed', 'Speed'), ('Luck', 'Luck'), ('Charisma', 'Charisma')], max_length=100, primary_key=True, serialize=False)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/stats/')),
                ('description', models.TextField(blank=True, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ViolationObject',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(choices=[('Physical', 'Physical'), ('Mental', 'Mental'), ('Energy', 'Energy'), ('Heat', 'Heat'), ('Cold', 'Cold'), ('Light', 'Light'), ('Darkness', 'Darkness'), ('None', 'None')], max_length=100, primary_key=True, serialize=False)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/violation/')),
                ('description', models.TextField(blank=True, null=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
