# Generated by Django 5.1.4 on 2025-06-14 13:01

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_statobject_violationobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionAnomaly',
            fields=[
                ('gameobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.gameobject')),
                ('known', models.BooleanField(default=False)),
                ('level', models.PositiveIntegerField(default=1)),
                ('effect', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Neutral', 'Neutral')], default=apps.core.models.DimensionAnomalyEffect['Positive'], max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.gameobject',),
        ),
    ]
