# Generated by Django 5.2.3 on 2025-06-27 07:10

import django.db.models.deletion
from django.db import migrations, models


def delete_objects_with_null_campaign(apps, schema_editor):
    GameObject = apps.get_model('core', 'GameObject')

    # Delete all objects with NULL campaign values
    GameObject.objects.filter(campaign__isnull=True).delete()


def reverse_func(apps, schema_editor):
    # No need to do anything when reversing
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_dimensionanomaly"),
        ("game", "0005_ensure_default_campaign"),
    ]

    operations = [
        # First, delete objects with NULL campaign values
        migrations.RunPython(delete_objects_with_null_campaign, reverse_func),

        # Then, alter the field to be non-nullable
        migrations.AlterField(
            model_name="gameobject",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.campaign"
            ),
        ),
    ]
