# Generated by Django 5.2.3 on 2025-07-14 08:50

import apps.core.utils.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_gameobject_campaign"),
        ("world", "0013_positionconnection_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trigger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("search", "search"),
                            ("kill", "kill"),
                            ("interaction", "interaction"),
                            ("position", "position"),
                            ("useItem", "useItem"),
                            ("useSkill", "useSkill"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the trigger"),
                ),
                (
                    "game_object",
                    models.ForeignKey(
                        blank=True,
                        help_text="Item, NPC, Anomaly",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.gameobject",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional limit trigger to a specific location",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="world.location",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        help_text="Position in the game world",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="world.position",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(apps.core.utils.models.Tagged, models.Model),
        ),
    ]
