# Generated by Django 5.2.3 on 2025-07-14 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0042_character_template"),
        ("core", "0006_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="trigger",
            name="npc",
            field=models.ForeignKey(
                blank=True,
                help_text="All NPCs that been created from this template will have this trigger",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="character.charactertemplate",
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="game_object",
            field=models.ForeignKey(
                blank=True,
                help_text="Item, Character, Anomaly",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.gameobject",
            ),
        ),
    ]
