# Generated by Django 5.2.3 on 2025-07-14 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_trigger_npc_alter_trigger_game_object"),
        ("items", "0009_worlditem_visibility"),
        ("school", "0009_alter_thepath_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="trigger",
            name="item",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional item that is required to trigger the action",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="items.item",
            ),
        ),
        migrations.AddField(
            model_name="trigger",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional skill that is required to trigger the action",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.skill",
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="game_object",
            field=models.ForeignKey(
                blank=True,
                help_text="Concreate - Item, Character, Anomaly",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.gameobject",
            ),
        ),
    ]
