# Generated by Django 5.2.3 on 2025-07-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_trigger_item_trigger_skill_alter_trigger_game_object"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trigger",
            name="type",
            field=models.CharField(
                choices=[
                    ("search", "search"),
                    ("kill", "kill"),
                    ("interaction", "interaction"),
                    ("position", "position"),
                    ("useItem", "useItem"),
                    ("useSkill", "useSkill"),
                    ("custom", "custom"),
                ],
                max_length=20,
            ),
        ),
    ]
