# Generated by Django 5.2.3 on 2025-07-14 08:50

import apps.core.utils.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0006_trigger"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField()),
                (
                    "items",
                    models.JSONField(
                        default=list, help_text="List of items with itemId and quantity"
                    ),
                ),
                (
                    "tokens",
                    models.JSONField(
                        default=list,
                        help_text="List of tokens with tokenId and quantity",
                    ),
                ),
                ("experience", models.PositiveIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
            bases=(apps.core.utils.models.Tagged, models.Model),
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text="List of tags for the story"
                    ),
                ),
                (
                    "image",
                    models.URLField(
                        blank=True,
                        help_text="Optional URL to an image representing the story",
                        null=True,
                    ),
                ),
                (
                    "canonical",
                    models.BooleanField(
                        default=False,
                        help_text="Default to false, need review by the Owner",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Stories",
            },
            bases=(apps.core.utils.models.Tagged, models.Model),
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("all", "All"), ("any", "Any"), ("none", "None")],
                        default="all",
                        max_length=10,
                    ),
                ),
                (
                    "triggers",
                    models.ManyToManyField(
                        related_name="conditions", to="core.trigger"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(apps.core.utils.models.Tagged, models.Model),
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "image",
                    models.URLField(
                        blank=True,
                        help_text="Optional URL to an image representing the chapter",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of the chapter within the story"
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="story.story",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("story", "order")},
            },
            bases=(apps.core.utils.models.Tagged, models.Model),
        ),
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "image",
                    models.URLField(
                        blank=True,
                        help_text="Optional URL to an image representing the quest",
                        null=True,
                    ),
                ),
                (
                    "cycle_limit",
                    models.PositiveIntegerField(
                        default=50, help_text="Time limit in cycles (1 cycle = 1 turn)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of the quest within the chapter"
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quests",
                        to="story.chapter",
                    ),
                ),
                (
                    "objectives",
                    models.ManyToManyField(
                        blank=True,
                        related_name="objective_quests",
                        to="story.condition",
                    ),
                ),
                (
                    "starters",
                    models.ManyToManyField(
                        blank=True, related_name="starter_quests", to="story.condition"
                    ),
                ),
                (
                    "on_failure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failure_quests",
                        to="story.reward",
                    ),
                ),
                (
                    "on_success",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="success_quests",
                        to="story.reward",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("chapter", "order")},
            },
            bases=(apps.core.utils.models.Tagged, models.Model),
        ),
    ]
