# Generated by Django 5.2.3 on 2025-07-14 09:02

import apps.core.utils.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0003_alter_charactercurrency_character"),
        ("effects", "0004_activeeffect_ends_in"),
        ("items", "0009_worlditem_visibility"),
        ("story", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reward",
            name="items",
        ),
        migrations.RemoveField(
            model_name="reward",
            name="tokens",
        ),
        migrations.AlterField(
            model_name="chapter",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional URL to an image representing the chapter",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="quest",
            name="cycle_limit",
            field=models.PositiveIntegerField(
                blank=True,
                default=50,
                help_text="Time limit in cycles (1 cycle = 1 turn)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="quest",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional URL to an image representing the quest",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional URL to an image representing the story",
                null=True,
                upload_to="",
            ),
        ),
        migrations.CreateModel(
            name="EffectReward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=0, help_text="Duration of the effect in turns"
                    ),
                ),
                (
                    "effect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effect_rewards",
                        to="effects.effect",
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effects",
                        to="story.reward",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(apps.core.utils.models.Tagged, models.Model),
        ),
        migrations.CreateModel(
            name="ItemReward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.PositiveIntegerField(
                        default=0, help_text="Amount of items to reward"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_rewards",
                        to="items.item",
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="story.reward",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(apps.core.utils.models.Tagged, models.Model),
        ),
        migrations.CreateModel(
            name="TokenReward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.PositiveIntegerField(
                        default=0, help_text="Amount of tokens to reward"
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="story.reward",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_rewards",
                        to="currency.currencytoken",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(apps.core.utils.models.Tagged, models.Model),
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional URL to an image representing the note",
                        null=True,
                        upload_to="",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of the note within the quest"
                    ),
                ),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="story.quest",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("quest", "order")},
            },
            bases=(apps.core.utils.models.Tagged, models.Model),
        ),
    ]
