# Generated by Django 5.2.4 on 2025-10-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_remove_reward_items_remove_reward_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional URL to an image representing the chapter', null=True, upload_to='story/chapter'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional URL to an image representing the story', null=True, upload_to='story/story'),
        ),
    ]
