# Generated by Django 5.1.4 on 2025-01-03 11:20

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0019_fix_content_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shield',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(choices=apps.core.models.ImpactViolationType.choices, default=apps.core.models.ImpactViolationType['NONE'], max_length=255, primary_key=True, serialize=False)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/shields/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActiveShield',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycles_left', models.PositiveIntegerField(default=1)),
                ('health', models.PositiveIntegerField(default=1)),
                ('efficiency', models.FloatField(default=1)),
                ('level', models.PositiveIntegerField(default=1)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shields', to='character.character')),
                ('shield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shields.shield')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
