# Generated by Django 5.1.4 on 2025-01-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shield',
            name='base_efficiency',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='shield',
            name='base_health',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
