# Generated by Django 5.1.4 on 2025-01-03 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0019_fix_content_types'),
        ('shields', '0002_shield_base_efficiency_shield_base_health'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activeshield',
            unique_together={('shield', 'target')},
        ),
    ]
