# Generated by Django 5.1.4 on 2025-01-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shields', '0003_alter_activeshield_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeshield',
            name='efficiency',
        ),
        migrations.RemoveField(
            model_name='activeshield',
            name='level',
        ),
    ]
