# Generated by Django 5.2.4 on 2025-08-27 09:00

import apps.core.models.core
import apps.core.utils.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("action", "0031_characteraction_fight"),
        ("character", "0044_alter_character_fight"),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("difficulty", models.PositiveIntegerField(default=12)),
                ("description", models.TextField(blank=True, null=True)),
                ("dice_sides", models.PositiveIntegerField(default=20)),
                (
                    "stat",
                    models.CharField(
                        choices=[
                            ("Physical Strength", "Physical Strength"),
                            ("Mental Strength", "Mental Strength"),
                            ("Flow Resonance", "Flow Resonance"),
                            ("Concentration", "Concentration"),
                            ("Flow Manipulation", "Flow Manipulation"),
                            ("Flow Connection", "Flow Connection"),
                            ("Knowledge", "Knowledge"),
                            ("Speed", "Speed"),
                            ("Luck", "Luck"),
                            ("Charisma", "Charisma"),
                        ],
                        default=apps.core.models.core.CharacterStats["LUCK"],
                        max_length=255,
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="challenges_outcome",
                        to="action.dicerollresult",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenges",
                        to="character.character",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(apps.core.utils.models.Tagged, models.Model),
        ),
        migrations.CreateModel(
            name="ChallengeModifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="challenge_modifiers/"
                    ),
                ),
                ("value", models.IntegerField()),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifiers",
                        to="dice.challenge",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(apps.core.utils.models.Tagged, models.Model),
        ),
    ]
