# Generated by Django 5.2.4 on 2025-08-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="advantage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="challenge",
            name="disadvantage",
            field=models.BooleanField(default=False),
        ),
    ]
