# Generated by Django 5.0.6 on 2024-12-23 10:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/school/')),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThePath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/path/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('description', models.TextField()),
                ('multi_target', models.BooleanField()),
                ('type', models.CharField(choices=[('attack', 'Attack'), ('defense', 'Defense'), ('heal', 'Heal'), ('buff', 'Buff'), ('debuff', 'Debuff'), ('utility', 'Utility')], default='attack', max_length=10)),
                ('impact', models.JSONField(default=list, help_text='A list of dictionaries representing the impact of the skill.', verbose_name='Impact')),
                ('cost', models.JSONField(default=list, help_text='A list of dictionaries representing the cost of the skill.', verbose_name='Cost')),
                ('effect', models.JSONField(blank=True, default=list, help_text='A list of dictionaries representing the effects of the skill.', verbose_name='Effect')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/skill/')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='school.school')),
            ],
            options={
                'ordering': ['grade'],
            },
        ),
        migrations.AddField(
            model_name='school',
            name='path',
            field=models.ManyToManyField(to='school.thepath'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('name', 'school'), name='unique_skill_name_per_school'),
        ),
    ]
