# Generated by Django 5.1.4 on 2024-12-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='is_default',
            new_name='is_base',
        ),
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('attack', 'Attack'), ('defense', 'Defense'), ('heal', 'Heal'), ('buff', 'Buff'), ('debuff', 'Debuff'), ('utility', 'Utility'), ('special', 'Special')], default='attack', max_length=10),
        ),
    ]
