# Generated by Django 5.0.6 on 2024-06-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="cost",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="skill",
            name="effect",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="skill",
            name="impact",
            field=models.JSONField(default=list),
        ),
    ]
