# Generated by Django 5.1.4 on 2024-12-30 15:45

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_rename_is_default_school_is_base_alter_skill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=apps.core.models.SkillTypes.choices, default=apps.core.models.SkillTypes['ATTACK'], max_length=10),
        ),
    ]
