# Generated by Django 5.0.6 on 2024-06-09 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_skill_cost_skill_effect_skill_impact"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="school.school",
            ),
        ),
    ]
