# Generated by Django 5.1.4 on 2025-01-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_skill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='path',
            field=models.ManyToManyField(blank=True, null=True, to='school.thepath'),
        ),
    ]
