# Generated by Django 5.0.6 on 2024-06-09 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0003_skill_school"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ["grade"]},
        ),
        migrations.AlterField(
            model_name="skill",
            name="grade",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="skill",
            constraint=models.UniqueConstraint(
                fields=("name", "school"), name="unique_skill_name_per_school"
            ),
        ),
    ]
