# Generated by Django 5.1.4 on 2025-01-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_school_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='path',
            field=models.ManyToManyField(blank=True, related_name='schools', to='school.thepath'),
        ),
    ]
