# Generated by Django 5.0.6 on 2024-06-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0004_alter_skill_options_alter_skill_grade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="type",
            field=models.CharField(
                choices=[
                    ("attack", "Attack"),
                    ("defense", "Defense"),
                    ("heal", "Heal"),
                    ("buff", "Buff"),
                    ("debuff", "Debuff"),
                    ("utility", "Utility"),
                ],
                default="attack",
                max_length=10,
            ),
        ),
    ]
