# Generated by Django 5.1.4 on 2025-02-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_school_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='impact',
            field=models.JSONField(blank=True, default=list, help_text='A list of dictionaries representing the impact of the skill.', verbose_name='Impact'),
        ),
    ]
