# Generated by Django 5.1.4 on 2025-06-14 07:55

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_skill_impact'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='special',
            field=models.CharField(choices=apps.core.models.SpecialSkillType.choices, default=apps.core.models.SpecialSkillType['REGULAR_ACTION'], help_text='Special type of the skill', max_length=30, verbose_name='Special Type'),
        ),
    ]
