# Generated by Django 5.1.4 on 2025-06-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_skill_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='immediate',
            field=models.BooleanField(default=False, help_text='If true, the skill will be performed immediately'),
        ),
    ]
