# Generated by Django 5.2.3 on 2025-06-22 12:50

from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):
    dependencies = [
        ('school', '0008_skill_immediate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thepath',
            name='name',
            field=models.CharField(choices=[('Path of John', 'Path of John'), ('Path of JSon', 'Path of JSon'),
                                            ('Not Chosen', 'Not Chosen')], db_index=True,
                                   default=apps.core.models.TheChosenPath['MAGIC_JSON'], max_length=255, unique=True),
        ),
    ]
