# Generated by Django 5.2.4 on 2025-08-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0009_alter_thepath_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="game_master_only",
            field=models.BooleanField(
                default=False,
                help_text="If true, only game masters can create skills in this school",
            ),
        ),
    ]
