# Generated by Django 5.2.4 on 2025-10-05 13:16

import apps.core.utils.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DXDate',
            fields=[
                ('dxCycle', models.BigIntegerField(help_text='Cycle number (dxDay = 100 cycle; dxYear = 10,000; dxMonth = 12)', primary_key=True, serialize=False)),
                ('BAG', models.BooleanField(default=False, help_text='Before Active Glow')),
            ],
            options={
                'verbose_name': 'DX Date',
                'verbose_name_plural': 'DX Dates',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseItemTag',
            fields=[
                ('label', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Knowledge Base Item Tag',
                'verbose_name_plural': 'Knowledge Base Item Tags',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('events', 'Events'), ('location', 'Location'), ('character', 'Character')], help_text='Category of the knowledge base item', max_length=20)),
                ('dxCycle', models.BigIntegerField(help_text='Cycle number (dxDay = 100 cycle; dxYear = 10,000; dxMonth = 12)')),
                ('description', models.TextField(help_text='Description of the knowledge base item')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Additional metadata as JSON (e.g., {'customField': 'value'})")),
                ('breadcrumbs', models.ManyToManyField(blank=True, help_text='Related knowledge base items forming breadcrumb navigation', related_name='child_items', to='knowledge_base.knowledgebaseitem')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags associated with this knowledge base item', related_name='knowledge_base_items', to='knowledge_base.knowledgebaseitemtag')),
            ],
            options={
                'verbose_name': 'Knowledge Base Item',
                'verbose_name_plural': 'Knowledge Base Items',
                'ordering': ['dxCycle', 'category'],
            },
            bases=(apps.core.utils.models.Tagged, models.Model),
        ),
    ]
