# Generated by Django 5.2.4 on 2025-10-11 09:44

import apps.core.utils.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def create_document_categories(apps, schema_editor):
    """Create all document categories from DocumentCategoryEnum"""
    DocumentCategory = apps.get_model('knowledge_base', 'DocumentCategory')
    
    # Define categories matching DocumentCategoryEnum
    categories = [
        ('events', 'Events'),
        ('rules', 'Rules'),
        ('lore', 'Lore'),
        ('stories', 'Stories'),
        ('guides', 'Guides'),
        ('items', 'Items'),
        ('characters', 'Characters'),
        ('locations', 'Locations'),
        ('places', 'Places'),
        ('factions', 'Factions'),
        ('creatures', 'Creatures'),
        ('skills', 'Skills'),
        ('spells', 'Spells'),
        ('abilities', 'Abilities'),
        ('other', 'Other'),
    ]
    
    for name, description in categories:
        DocumentCategory.objects.get_or_create(name=name, defaults={'description': description})


def reverse_create_document_categories(apps, schema_editor):
    """Remove all document categories"""
    DocumentCategory = apps.get_model('knowledge_base', 'DocumentCategory')
    DocumentCategory.objects.all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_glow', models.BooleanField(default=True)),
                ('sol', models.PositiveBigIntegerField(default=0, help_text="Number of sol's since the start of the calendar")),
                ('solar_year', models.PositiveBigIntegerField(default=0, help_text='Number of solar years since the start of the calendar')),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.core.utils.models.Tagged, models.Model),
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('name', models.CharField(choices=[('events', 'Events'), ('rules', 'Rules'), ('lore', 'Lore'), ('stories', 'Stories'), ('guides', 'Guides'), ('items', 'Items'), ('characters', 'Characters'), ('locations', 'Locations'), ('places', 'Places'), ('factions', 'Factions'), ('creatures', 'Creatures'), ('skills', 'Skills'), ('spells', 'Spells'), ('abilities', 'Abilities'), ('other', 'Other')], default='other', max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='document-categories/')),
            ],
        ),
        migrations.RunPython(create_document_categories, reverse_create_document_categories),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('categories', models.ManyToManyField(related_name='documents', to='knowledge_base.documentcategory')),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.core.utils.models.Tagged, models.Model),
        ),
        migrations.CreateModel(
            name='TimeLineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='knowledge_base.datetimeinfo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='knowledge_base.document')),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['date_time__solar_year', 'date_time__sol'],
            },
            bases=(apps.core.utils.models.Tagged, models.Model),
        ),
    ]
