# Generated by Django 5.1.4 on 2025-01-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactercurrency',
            name='character',
            field=models.UUIDField(),
        ),
    ]
