# Generated by Django 5.1.4 on 2025-01-01 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0017_alter_characterbiography_character'),
        ('currency', '0002_alter_charactercurrency_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactercurrency',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='character.character'),
        ),
    ]
