# Generated by Django 5.0.6 on 2024-06-09 12:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="age",
            field=models.PositiveIntegerField(
                max_length=3,
                validators=[
                    django.core.validators.MinValueValidator(18),
                    django.core.validators.MaxValueValidator(200),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="CharacterStatSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("health_points", models.IntegerField(default=100)),
                ("energy_points", models.IntegerField(default=100)),
                ("physical_strength", models.IntegerField(default=10)),
                ("mental_strength", models.IntegerField(default=10)),
                ("luck", models.IntegerField(default=10)),
                ("speed", models.IntegerField(default=10)),
                ("concentration", models.IntegerField(default=1)),
                ("flow_manipulation", models.IntegerField(default=1)),
                ("flow_connection", models.IntegerField(default=1)),
                ("knowledge", models.IntegerField(default=1)),
                ("flow_resonance", models.IntegerField(default=1)),
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="player.character",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="CharacterStats",
        ),
    ]
