# Generated by Django 5.0.6 on 2024-06-09 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player", "0002_alter_character_age_alter_character_gender_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="characterstatset",
            name="character",
        ),
        migrations.AddField(
            model_name="character",
            name="stats",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="player.characterstatset",
            ),
        ),
    ]
