# Generated by Django 5.0.6 on 2024-06-09 16:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player", "0003_remove_characterstatset_character_character_stats"),
        ("school", "0001_initial"),
        ("world", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="activities",
        ),
        migrations.RemoveField(
            model_name="character",
            name="current_location",
        ),
        migrations.RemoveField(
            model_name="character",
            name="dimension",
        ),
        migrations.RemoveField(
            model_name="character",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="character",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="character",
            name="place_of_birth",
        ),
        migrations.RemoveField(
            model_name="character",
            name="rank",
        ),
        migrations.RemoveField(
            model_name="character",
            name="skills",
        ),
        migrations.RemoveField(
            model_name="character",
            name="stats",
        ),
        migrations.RemoveField(
            model_name="violation",
            name="player",
        ),
        migrations.RemoveField(
            model_name="effect",
            name="impacts",
        ),
        migrations.RemoveField(
            model_name="violation",
            name="effects",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="effects",
        ),
        migrations.RemoveField(
            model_name="school",
            name="impacts",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="impacts",
        ),
        migrations.RemoveField(
            model_name="school",
            name="path",
        ),
        migrations.RemoveField(
            model_name="school",
            name="required_rank",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="school",
        ),
        migrations.AlterModelOptions(
            name="rank",
            options={"ordering": ["experience_needed"], "verbose_name_plural": "Ranks"},
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "age",
                    models.PositiveIntegerField(
                        max_length=3,
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("bio", models.TextField()),
                ("experience", models.IntegerField()),
                ("current_health_points", models.IntegerField()),
                ("current_energy_points", models.IntegerField()),
                ("current_active_points", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "current_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="players",
                        to="world.location",
                    ),
                ),
                (
                    "dimension",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="world.dimension",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="player.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "path",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="school.thepath",
                    ),
                ),
                (
                    "place_of_birth",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="where_born",
                        to="world.location",
                    ),
                ),
                (
                    "rank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="player.rank",
                    ),
                ),
                (
                    "stats",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character",
                        to="player.characterstatset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Activity",
        ),
    ]
