# Generated by Django 5.0.6 on 2024-06-09 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0003_alter_client_main_character"),
        ("game", "0002_alter_session_player"),
        ("player", "0004_remove_character_activities_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Character",
        ),
        migrations.DeleteModel(
            name="Violation",
        ),
        migrations.DeleteModel(
            name="Effect",
        ),
        migrations.DeleteModel(
            name="Impact",
        ),
        migrations.DeleteModel(
            name="ThePath",
        ),
        migrations.DeleteModel(
            name="School",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
    ]
