# Generated by Django 5.0.6 on 2024-06-09 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player", "0005_delete_character_delete_violation_delete_effect_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rank",
            name="grade",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
