# Generated by Django 5.0.6 on 2024-06-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player", "0006_rank_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rank",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
