# Generated by Django 5.0.6 on 2024-06-14 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fight", "0001_initial"),
        ("player", "0008_alter_player_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="fight",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fight.fight",
            ),
        ),
    ]
