# Generated by Django 5.0.6 on 2024-06-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("player", "0009_player_fight"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="school_slots",
            field=models.PositiveIntegerField(default=2),
        ),
    ]
